/* auto-generated by NAPI-RS — platform binary loader */
/* eslint-disable */
/* prettier-ignore */

const { existsSync, readFileSync } = require('fs')
const { join } = require('path')

const { platform, arch } = process

let nativeBinding = null
let localFileExisted = false
let loadError = null

function isMusl() {
  // For Node 12, use `os.cpus()` heuristic; otherwise check /usr/bin/ldd
  if (platform !== 'linux') return false
  try {
    const ldd = readFileSync('/usr/bin/ldd', 'utf8')
    return ldd.includes('musl')
  } catch {
    return false
  }
}

switch (platform) {
  case 'darwin':
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(join(__dirname, 'tts-native.darwin-x64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./tts-native.darwin-x64.node')
          } else {
            nativeBinding = require('@animus/tts-native-darwin-x64')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = existsSync(join(__dirname, 'tts-native.darwin-arm64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./tts-native.darwin-arm64.node')
          } else {
            nativeBinding = require('@animus/tts-native-darwin-arm64')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on macOS: ${arch}`)
    }
    break
  case 'linux':
    switch (arch) {
      case 'x64':
        if (isMusl()) {
          throw new Error('musl libc is not supported')
        } else {
          localFileExisted = existsSync(join(__dirname, 'tts-native.linux-x64-gnu.node'))
          try {
            if (localFileExisted) {
              nativeBinding = require('./tts-native.linux-x64-gnu.node')
            } else {
              nativeBinding = require('@animus/tts-native-linux-x64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'arm64':
        if (isMusl()) {
          throw new Error('musl libc is not supported')
        } else {
          localFileExisted = existsSync(join(__dirname, 'tts-native.linux-arm64-gnu.node'))
          try {
            if (localFileExisted) {
              nativeBinding = require('./tts-native.linux-arm64-gnu.node')
            } else {
              nativeBinding = require('@animus/tts-native-linux-arm64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      default:
        throw new Error(`Unsupported architecture on Linux: ${arch}`)
    }
    break
  case 'win32':
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(join(__dirname, 'tts-native.win32-x64-msvc.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./tts-native.win32-x64-msvc.node')
          } else {
            nativeBinding = require('@animus/tts-native-win32-x64-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = existsSync(join(__dirname, 'tts-native.win32-arm64-msvc.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./tts-native.win32-arm64-msvc.node')
          } else {
            nativeBinding = require('@animus/tts-native-win32-arm64-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Windows: ${arch}`)
    }
    break
  default:
    throw new Error(`Unsupported OS: ${platform}, architecture: ${arch}`)
}

if (!nativeBinding) {
  if (loadError) {
    throw loadError
  }
  throw new Error(
    `Failed to load native binding. ` +
    `Try running: npm run build -w @animus/tts-native\n` +
    `Platform: ${platform}, Arch: ${arch}`
  )
}

const { PocketTts, VoiceState } = nativeBinding

module.exports.PocketTTS = PocketTts
module.exports.VoiceState = VoiceState
